import Link from 'next/link'

export const metadata = {
  title: 'Calculator',
  description: 'Generated by Next.js'
}

/* Creating an array of objects that will be used to create the links in the header. */
const links = [
  {
    label: 'Home',
    route: '/'
  },
  {
    label: 'History',
    route: '/history'
  }
]

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body>
        <header className=' bg-blue-600 h-[8vh] flex items-center'>
          <nav>
            <ul className=' text-xl font-semibold flex flex-row justify-start'>
              {links.map(({ label, route }) => (
                <li key={route} className=' px-3'>
                  <Link href={route}>
                    {label}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
